version: "3"
services:
 car-app:
   container_name: car-app
   image: latest123/car-app
   environment:
     - MONGO_DB=car-app
     - MONGO_HOST=mongodb
   build: .
   ports:
     - "3000:3000"
   links:
     - mongodb
 mongodb:
   container_name: mongodb
   image: mongo
   volumes:
     - ./data:/data/db
   ports:
     - '27017:27017'